image: docker:stable

services:
- docker:dind

stages: # List of stages for jobs, and their order of execution
  - dc
  #- build
  #- test
  # - deploy

dc-job:
  stage: dc
  image: docker/compose
  script:
    - docker-compose version
    - docker-compose up -d
  after_script:
    - docker-compose down

# build-job: # This job runs in the build stage, which runs first.
#   stage: build
#   before_script:
#     - docker-compose up -d
#   script:
#     - echo "Containers built."
#     - docker-compose exec fastapiapp pytest -s
#     - docker-compose exec fastapiapp pylint
#   after_script:
#     - docker-compose down
