stages: # List of stages for jobs, and their order of execution
  - build
  #- test
  # - deploy

build-job: # This job runs in the build stage, which runs first.
  stage: build
  before_script:
    - docker-compose up -d
  script:
    - echo "Containers built."
    - docker-compose exec fastapiapp pytest -s
    - docker-compose exec fastapiapp pylint
  after_script:
    - docker-compose down
