version: '3'
networks:
  app-tier:
    driver: bridge
services:
  fastapiapp:
    container_name: docker-fastapi
    # Build the Dockerfile that is in the api directory
    build: ./api
    ports:
      - "8000:8000"
    environment: 
      - MONGODB_CONNSTRING=mongodb://admin:password@mongodb
    # Mount the api directory within the container at /home/fastapi/app/api
    volumes:
      - ./api:/home/fastapi/app/api
      # This blank directory exists so that the local virtual environment doesn't get
      # used by the container. https://stackoverflow.com/questions/29181032/add-a-volume-to-docker-but-exclude-a-sub-folder#comment81906046_47153236
      - ./api/blank:/home/fastapi/app/api/env

    entrypoint: ["sh", "/home/fastapi/app/api/start.sh"]
    depends_on:
      - mongodb
    networks:
      - app-tier
  mongodb:
    container_name: docker-fastapi-mongodb
    # Using this image because of https://github.com/docker-library/mongo/issues/329#issuecomment-852129727
    image: bitnami/mongodb:latest
    environment:
      MONGODB_DATABASE: mydatabase
      MONGODB_ROOT_PASSWORD: password
      MONGODB_ROOT_USER: admin
      TEST_MONGO_URI: mongodb://admin:password@mongodb
    networks:
      - app-tier
    # To persist the data outside the container
    volumes:
      - mongodb_data_container:/data/db
  # For GitLab
  gitlab:
    # TODO: change hostname and external url to http://gitlab.dbuckley.dev
    # expose gitlab via ip: https://docs.gitlab.com/ee/install/docker.html#run-gitlab-on-a-public-ip-address
    image: 'gitlab/gitlab-ce:latest'
    container_name: gitlab
    restart: always
    hostname: 'localhost'
    environment:
      # GITLAB_OMNIBUS_CONFIG: |
      #   external_url 'http://localhost:8980'
      #   gitlab_rails['gitlab_shell_ssh_port'] = 8922      
      GITLAB_OMNIBUS_CONFIG: |
        gitlab_rails['gitlab_shell_ssh_port'] = 8922
    ports:
      - '8943:443'
      - '8980:80'
      - '8922:22'
    volumes:
      - 'gitlab_config:/etc/gitlab'
      - 'gitlab_logs:/var/log/gitlab'
      - 'gitlab_data:/var/opt/gitlab'
    shm_size: '256m'
    networks:
      - app-tier
  dind:
    # Docker in Docker, so that GitLab can run Docker containers for its pipelines.
    image: docker:20-dind
    restart: always
    privileged: true
    environment:
      DOCKER_TLS_CERTDIR: ""
    command:
      - --storage-driver=overlay2
    networks:
      - app-tier
  gitlab-runner:
    # Runtime for pipelines
    restart: always
    image: gitlab/gitlab-runner:latest
    depends_on:
      - dind
    environment:
      DOCKER_HOST: "tcp://dind:2375"
    volumes:
      - './config:/etc/gitlab-runner'
    networks:
      - app-tier
  register-runner:
    # Create a runner
    # https://forum.gitlab.com/t/example-gitlab-runner-docker-compose-configuration/67344
    restart: 'no'
    image: gitlab/gitlab-runner:latest
    depends_on:
      - dind
    environment:
      - CI_SERVER_URL=${CI_SERVER_URL}
      - REGISTRATION_TOKEN=${REGISTRATION_TOKEN}
      - RUNNER_NAME=${RUNNER_NAME}
    command:
      - register 
      - --non-interactive
      - --locked=false
      - --registration-token=${REGISTRATION_TOKEN}
      - --url=${CI_SERVER_URL}
      - --clone-url=${CI_SERVER_URL}
      - --name=${RUNNER_NAME}
      - --executor=docker
      - --docker-image=docker:20-dind
      - --docker-volumes=/var/run/docker.sock:/var/run/docker.sock
    volumes:
      - './config:/etc/gitlab-runner'
    networks:
      - app-tier

volumes:
  mongodb_data_container: {}
  gitlab_config: {}
  gitlab_data: {}
  gitlab_logs: {}